version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "8080"
      MONGO_DB_URI: "mongodb://mongodb:27017"
      DATABASE_NAME: "deck"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
